name: Main Workflow
on:
  push:
    branches:
      - main
      - release.*
  pull_request:

jobs:
  dev_increment:
    permissions:
      contents: write
      actions: read
      packages: write

    runs-on: ubuntu-latest
    with:
      container:
        image: ghcr.io/greenqloud/cvi/sbisht/testdummy:v1
        options: -v /var/run/docker.sock:/var/run/docker.sock --user root
    steps:

      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'

      - name: Configure Git
        run: |
          git config --global user.email "Shivam.Bisht@netapp.com"
          git config --global user.name "netappshivam"

      - name: Run dev logic
        id: dev_logic
        run: vsactl tag dev_increment

      - name: Set Tag
        run: |
          NEW_TAG=${{ steps.dev_logic.outputs.new_tag }}
          echo "New tag: $NEW_TAG"
          git tag $NEW_TAG
          git push origin $NEW_TAG

  release_branch:
    permissions:
      contents: write
      actions: read
      packages: write

    runs-on: ubuntu-latest
    with:
      container:
        image: ghcr.io/greenqloud/cvi/sbisht/testdummy:v1
        options: -v /var/run/docker.sock:/var/run/docker.sock --user root

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'

      - name: Configure Git
        run: |
          git config --global user.email "Shivam.Bisht@netapp.com"
          git config --global user.name "netappshivam"

#      - name: Build release binary
#        run: |
#          go build -o ./cicd/release_logic_binary ./cicd
#          chmod +x ./cicd/release_logic_binary

      - name: Run release logic
        id: release_logic_binary
        run: vsactl tag release

      - name: Set Tag
        run: |
          NEW_TAG=${{ steps.release_logic_binary.outputs.new_tag }}
          git tag $NEW_TAG
          git push origin $NEW_TAG
          
