name: Main Workflow
on:
  push:
    branches:
      - main
      - release.*
      - cobra
  pull_request:

jobs:


  build_cicd:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/greenqloud/cvi/sbisht/testdummy:v1
      options: -v /var/run/docker.sock:/var/run/docker.sock --user root
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Log in to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}  # TODO: use Github bot account here
          password: ${{ secrets.DOCKER_PASSWORD }}  # TODO: use Github bot account here

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}  # TODO: use Github bot account here
          password: ${{ secrets.DOCKER_PASSWORD }}   # TODO: use Github bot account here

  dev_increment:
    needs: [build_cicd]
    permissions:
      contents: write
      actions: read
      packages: write

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/greenqloud/cvi/sbisht/testdummy:v1
      options: -v /var/run/docker.sock:/var/run/docker.sock --user root
    steps:

      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'

      - name: Configure Git
        run: |
          git config --global user.email "Shivam.Bisht@netapp.com"
          git config --global user.name "netappshivam"

      - name: Run dev logic
        id: dev_logic
        run: vsactl tag dev_increment

      - name: Set Tag
        run: |
          NEW_TAG=${{ steps.dev_logic.outputs.new_tag }}
          echo "New tag: $NEW_TAG"
          git tag $NEW_TAG
          git push origin $NEW_TAG

  release_branch:
    needs: [build_cicd]
    permissions:
      contents: write
      actions: read
      packages: write

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/greenqloud/cvi/sbisht/testdummy:v1
      options: -v /var/run/docker.sock:/var/run/docker.sock --user root

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'

      - name: Configure Git
        run: |
          git config --global user.email "Shivam.Bisht@netapp.com"
          git config --global user.name "netappshivam"

#      - name: Build release binary
#        run: |
#          go build -o ./cicd/release_logic_binary ./cicd
#          chmod +x ./cicd/release_logic_binary

      - name: Run release logic
        id: release_logic_binary
        run: vsactl tag release

      - name: Set Tag
        run: |
          NEW_TAG=${{ steps.release_logic_binary.outputs.new_tag }}
          git tag $NEW_TAG
          git push origin $NEW_TAG
          
