name: Main Workflow
on:
  push:
    branches:
      - main
      - release.*
  pull_request:

jobs:
  dev_increment:
    permissions:
      contents: write
      actions: read
      packages: write

    runs-on: ubuntu-latest
    steps:

      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'

      - name: Build dev binary
        run: |
          go build -o ./cicd/dev_logic_binary ./cicd
          chmod +x ./cicd/dev_logic_binary

      - name: Run dev logic
        id: abcd
        run: ./cicd/dev_logic_binary dev

      - name: Configure Git
        run: |
            git config --global user.email "Shivam.Bisht@netapp.com"
            git config --global user.name "netappshivam"

      - name: Set Tag
        run: |
          NEW_TAG=${{ steps.abcd.outputs.newTag1 }}
          echo "New tag: $NEW_TAG"
          git tag $NEW_TAG
          git push origin $NEW_TAG

  release_branch:
    permissions:
      contents: write
      actions: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'

      - name: Build release binary
        run: |
          go build -o ./cicd/release_logic_binary ./cicd
          chmod +x ./cicd/release_logic_binary

      - name: Run release logic
        id: release_logic_binary
        run: ./cicd/release_logic_binary release

      - name: Configure Git
        run: |
            git config --global user.email "Shivam.Bisht@netapp.com"
            git config --global user.name "netappshivam"

      - name: Set Tag
        run: |
          NEW_TAG=${{ steps.release_logic_binary.outputs.newTag1 }}
          git tag $TAG_NAME
          git push origin $TAG_NAME
