name: Main Workflow
on:
  push:
    branches:
      - envvariable

jobs:

  dev_increment:
    permissions:
      contents: write
      actions: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'

      - name: Run dev logic
        id: dev_logic
        run: go run main.go tag release

      - name: Set Tag
        run: |
          NEW_TAG=${{ steps.dev_logic.outputs.TEST_TAG }}
          echo "New tag: $NEW_TAG"
          git tag $NEW_TAG
          git push origin $NEW_TAG
