name: Main Workflow
on:
  push:
    branches:
      - main
      - release.*
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  dev_increment:
    runs-on: [ ubuntu-22.04 ]
    container:
      image: ghcr.io/vcp-vsa-control-plane/vsactl:v1
      options: -v /var/run/docker.sock:/var/run/docker.sock --user root

    steps:
      - name: Install required packages
        run: |
          apt-get update
          apt-get install -y curl jq
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'

      - name: Build dev binary
        run: |
          go build -o ./cicd/dev_logic_binary ./cicd
          chmod +x ./cicd/dev_logic_binary

      - name: Run dev logic
        run: ./cicd/dev_logic_binary dev

  release_branch:
    runs-on: [ ubuntu-22.04 ]
    container:
      image: ghcr.io/vcp-vsa-control-plane/vsactl:v1
      options: -v /var/run/docker.sock:/var/run/docker.sock --user root

    steps:
      - name: Install required packages
        run: |
          apt-get update
          apt-get install -y curl jq
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'

      - name: Build release binary
        run: |
          go build -o ./cicd/release_logic_binary ./cicd
          chmod +x ./cicd/release_logic_binary

      - name: Run release logic
        run: ./cicd/release_logic_binary release
