name: Go CI

on:
  push:
    branches:
        - main
        - Tag_branch

  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow read and write access to the repository contents
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: '${{ secrets.GH_PAT }}'

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'

      - name: Install dependencies
        run: go mod tidy

#      - name: Run tests
#        run: go test ./...

  tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow read and write access to the repository contents
      actions: read
      packages: write  # Add this line to allow pushing tags

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "Shivam.Bisht@netapp.com"
          git config --global user.name "netapppshivam"

      - name: Create and push a tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          TAG_NAME="v1.0.0"
          git tag $TAG_NAME
          git push origin $TAG_NAME
