name: Main Workflow
on:
  push:
    branches:
      - main
      - release.*
      - cobra
  pull_request:

jobs:

  dev_increment:
    permissions:
      contents: write
      actions: read
      packages: write

    runs-on: ubuntu-latest

    steps:

      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'

      - name: Configure Git
        run: |
          git config --global user.email "Shivam.Bisht@netapp.com"
          git config --global user.name "netappshivam"

      - name: Run dev logic
        id: dev_logic
        run: go run main.go tag dev_increment

      - name: Set Tag
        run: |
          NEW_TAG=${{ steps.dev_logic.outputs.new_tag }}
          echo "New tag: $NEW_TAG"
          git tag $NEW_TAG
          git push origin $NEW_TAG

  release_branch:
    permissions:
      contents: write
      actions: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'

      - name: Configure Git
        run: |
          git config --global user.email "Shivam.Bisht@netapp.com"
          git config --global user.name "netappshivam"

      - name: Run release logic
        id: release_logic_binary
        run: go run main.go tag release

      - name: Set Tag
        run: |
          NEW_TAG=${{ steps.release_logic_binary.outputs.new_tag }}
          git tag $NEW_TAG
          git push origin $NEW_TAG
          
