name: Final Tagging Workflow
on:
  workflow_dispatch:

jobs:
  final_tagging:
    permissions:
      contents: write
      actions: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: gh auth login
        run: |
          echo "Logging in to GitHub CLI"
          echo "${{ secrets.GHVSA_PAT }}" | gh auth login --with-token

      - name: Run Promotional logic
        id: promotional_logic_binary
        run: go run main.go tag promotional
        env:
          GH_PAT: ${{ secrets.GHVSA_PAT }}
          GITHUB_OUTPUT: $GITHUB_ENV

    outputs:
      finalTag: ${{ steps.promotional_logic_binary.outputs.FINAL_TAG }}
      finalBranch: ${{ steps.promotional_logic_binary.outputs.FINAL_BRANCH }}
      baseTagSHA: ${{ steps.promotional_logic_binary.outputs.BASE_TAG_SHA }}

  print:
    needs: [ final_tagging ]
    runs-on: ubuntu-latest
    steps:
      - name: Print RC and DEV tags
        run: |
          echo "Final Tag: ${{ needs.final_tagging.outputs.finalTag }}"
          echo "Final Branch: ${{ needs.final_tagging.outputs.finalBranch }}"
          echo "Base Tag SHA: ${{ needs.final_tagging.outputs.baseTagSHA }}"