name: branch creation

on:
  workflow_call:
  repository_dispatch:


jobs:

  create_branches:


    name: Create Branches
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          PATH="$PATH:/github/home/.local/bin"
          pip3 install shyaml

      - name: Copy scripts
        run: |
          cp ./dummy-pipeline/release_create.sh .
          chmod a+x ./release_create.sh

      - name: Create release branch
        run: ./release_create.sh ${{ steps.increment_tag.outputs.new_tag }}
        shell: bash
