name: Release Workflow
on:
  push:
    branches:
      - releasetag
  workflow_dispatch:

jobs:
  release_branch:
    permissions:
      contents: write
      actions: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'

      - name: Configure Git
        run: |
          USERNAME=${{ github.actor }}
          echo "Fetching email for $USERNAME"
          EMAIL=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" https://api.github.com/users/$USERNAME | jq -r '.email')
          if [ "$EMAIL" == "null" ]; then
            EMAIL="$USERNAME@users.noreply.github.com"
          fi
          echo "Using email: $EMAIL"
          echo "Using username: $USERNAME"

          git config --global user.email "$EMAIL"
          git config --global user.name "$USERNAME"

      - name: Run release logic
        id: release_logic_binary
        run: go run main.go tag release
#
#      - name: Set Tag
#        run: |
#          NEW_TAG=${{ steps.release_logic_binary.outputs.new_tag }}
#          git tag $NEW_TAG
#          git push origin $NEW_TAG
